homeassistant:
  # Name of the location where Home Assistant is running
  name: Soittila
  # Location required to calculate the time the sun rises and sets
  latitude: !secret location_latitude
  longitude: !secret location_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 80
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Helsinki
  customize: !include customize.yaml
    
# Show links to resources in log and frontend
#introduction:
system_health:
# Enables the frontend
frontend:

#mobile app
mobile_app:

# Enables configuration UI
config:

# Influx database
#
#influxdb:
#  host: localhost
#  port: 8086
#  database: home_assistant
#  username: hass
#  password: hass1234

#
logger:
  default: error
  logs:
    homeassistant.core: error
    homeassistant.components.http.ban: warning
    homeassistant.components.mqtt: error
http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction


# Ikea Trådfri Gateway
#tradfri:
#  host: 10.10.10.169
#  allow_tradfri_groups: true
sensor:
  - platform: yr

  - platform: mqtt
    name: "akwc"
    state_topic: "home/DHT/akwc/1/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "akwc kosteus"
    state_topic: "home/DHT/akwc/1/temp"
    unit_of_measurement: '%'
    value_template: '{{ value_json.Humidity }}'

  - platform: mqtt
    name: "ykpesuhuone Temp"
    state_topic: "home/ykpesuhuone/sensor"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "ykpesuhuone kosteus"
    state_topic: "home/ykpesuhuone/sensor"
    unit_of_measurement: '%'
    value_template: '{{ value_json.Humidity }}'

  - platform: mqtt
    name: "Keittio"
    state_topic: "home/sensor/raspi/keittio/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "Kodinhoitohuone"
    state_topic: "home/sensor/raspi/khh/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "Makuuhuone"
    state_topic: "home/sensor/raspi/makuuhuone/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "keittio lattia"
    state_topic: "home/sensor/raspi/keittioLattia/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "Olohuone"
    state_topic: "home/sensor/raspi/olohuone/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "Kodinhoitohuone lattia"
    state_topic: "home/sensor/raspi/khhLattia/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "ulkoE"
    state_topic: "home/sensor/raspi/ulkoE/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "varaaja keski" 
    state_topic: "home/sensor/raspi/varaajaMiddle/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "greeWaterCold"
    state_topic: "home/sensor/raspi/greeWaterCold/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "greeGasCold"
    state_topic: "home/sensor/raspi/greeGasCold/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "Ylakerta Makuuhuone"
    state_topic: "home/sensor/raspi/ykMH/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "verantaLattia"
    state_topic: "home/sensor/raspi/verantaLattia/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "veranta"
    state_topic: "home/sensor/raspi/veranta/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "ykAula"
    state_topic: "home/sensor/raspi/ykAula/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "ulkoP"
    state_topic: "home/sensor/raspi/ulkoP/temp"
    unit_of_measurement: '°C'
    value_template: '{{ value_json.Temp }}'

  - platform: mqtt
    name: "solarVoltage"
    state_topic: "home/solarlogger/voltage"
    unit_of_measurement: 'V'
    value_template: '{{ value_json.Voltage }}'

binary_sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/Ulkoovi"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: "door"

mqtt:
  broker: 10.10.10.2
  port: 1883
  client_id: home-assistant-1
  username: ha
  password: !secret mqtt_password
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

switch:
  - platform: mqtt
    name: "akwc flekti"
    state_topic: "home/sonoff/akwc/1/stat"
    command_topic: "home/sonoff/akwc/1"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "ykvh flekti"
    state_topic: "home/yk/flekti/1/stat"
    command_topic: "home/yk/flekti/1"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "ykphlattia"
    state_topic: "home/raspi/rele1/state"
    command_topic: "home/raspi/rele1"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "khhlattia"
    state_topic: "home/raspi/rele3/state"
    command_topic: "home/raspi/rele3"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "keittio"
    state_topic: "home/raspi/rele2/state"
    command_topic: "home/raspi/rele2"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "verantalattia"
    state_topic: "home/raspi/rele4/state"
    command_topic: "home/raspi/rele4"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "kiertovesipumppu"
    state_topic: "home/raspi/rele5/state"
    command_topic: "home/raspi/rele5"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "kiertovesipumppull"
    state_topic: "home/raspi/rele6/state"
    command_topic: "home/raspi/rele6"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "patterikiertoventtiili"
    state_topic: "home/raspi/rele7/state"
    command_topic: "home/raspi/rele7"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "attack heating"
    state_topic: "home/raspi/rele8/state"
    command_topic: "home/raspi/rele8"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "greeohjaus"
    state_topic: "home/raspi/2rele1/state"
    command_topic: "home/raspi/2rele1"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "makuuhuonepatteri"
    state_topic: "home/raspi/2rele2/state"
    command_topic: "home/raspi/2rele2"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: ""
    state_topic: "home/raspi/2rele3/state"
    command_topic: "home/raspi/2rele3"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "olohuonepatterit"
    state_topic: "home/raspi/2rele4/state"
    command_topic: "home/raspi/2rele4"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

  - platform: mqtt
    name: "greeheaterreset"
    state_topic: "home/raspi/3rele2/state"
    command_topic: "home/raspi/3rele2"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: false

light:
  - platform: mqtt
    name: "traktoritallisw"
    state_topic: "stat/traktoritallisw/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/traktoritallisw/POWER"
    qos: 1
    payload_on: 'ON'
    payload_off: 'OFF'
    payload_available: 'Online'
    payload_not_available: 'Offline'
    retain: false
 
  - platform: mqtt
    name: "autotallisw"
    state_topic: "stat/autotallisw/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/autotallisw/POWER"
    qos: 1
    payload_on: 'ON'
    payload_off: 'OFF'
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

  - platform: mqtt
    name: "sauna"
    state_topic: "stat/tasmota-4795/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/tasmota-4795/POWER"
    qos: 1
    payload_on: 'ON'
    payload_off: 'OFF'
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

notify:
  - name: HOME
    platform: pushbullet
    api_key: !secret pushbullet_apikey

group:
  default_view:
    view: yes
    entities:
      - group.ulko
      - group.sensorit
      - group.lattialammot
      - group.akwc
      - group.tekniikka
      - group.ulkovalot
      - group.autotalli
      - group.talo
      - group.solar
      - group.jouluvalot

  sensorit:
    name: Lämpötilat
    entities:
      - sensor.keittio
      - sensor.kodinhoitohuone
      - sensor.Makuuhuone
      - sensor.olohuone
      - sensor.ylakerta_makuuhuone
      - sensor.veranta
      - sensor.ykAula

  solar:
    name: solar logger
    view: no
    entities:
      - sensor.solarVoltage

  ulko:
    name: Ulkolämpötilat
    view: no
    entities:
      - sensor.ulkoE
      - sensor.ulkoP

  lattialammot:
    name: Lattia lämmöt
    view: yes
    entities:
      - sensor.kodinhoitohuone_lattia
      - sensor.keittio_lattia
      - sensor.khh_lattia
      - sensor.verantaLattia

  akwc:
    name: Pesuhuoneet
    view: yes
    entities:
      - sensor.akwc
      - sensor.akwc_kosteus
      - sensor.ykpesuhuone_Temp
      - sensor.ykpesuhuone_kosteus
      - switch.akwc_flekti
      - switch.ykvh_flekti

  tekniikka:
    name: Tekninentila
    view: yes
    entities:
      - sensor.varaaja_keski
      - sensor.greeWaterCold
      - sensor.greeGasCold
      - switch.greeohjaus  
      - switch.kiertovesipumppu
      - switch.kiertovesipumppull
      - switch.patterikiertoventtiili
      - switch.makuuhuonepatteri
      - switch.olohuonepatterit
      - switch.ykphlattia
      - switch.khhlattia
      - switch.keittio
      - switch.verantalattia
  ulkovalot:
    name: Ulkovalot
    entities:
      - light.ulko1
      - light.ulko2
      - light.ulko3
      - light.ulko4
      - light.ulko5
      - light.ulko6
      - light.ulko7
      - light.ulko8
      - light.ulko9
  autotalli:
    name: Autotalli valot
    entities:
      - light.autotalli1
      - light.autotalli2
      - light.autotalli3
  talo:
    name: Talo valot
    entities:
      - light.talo1
      - light.talo2
  jouluvalot:
    name: Jouluvalot
    view: yes
    entities:
      - light.autotallisw
      - light.traktoritallisw
      - light.sauna
  ulkovalot kaikki:
    control: hidden
    name: Kaikki Ulkovalot
    entities:
      - light.ulko1
      - light.ulko2
      - light.ulko3
      - light.ulko4
      - light.ulko5
      - light.ulko6
      - light.ulko7
      - light.ulko8
      - light.ulko9
      - light.talo1
      - light.talo2
      - light.autotalli1
      - light.autotalli2
      - light.autotalli3
  lampopumppu:
    view: no
    name: Lämpöpumppu
    entities:
      - switch.greeheaterreset 
automation: !include automations.yaml
